Add Missing Type Annotations
adafruit/Adafruit_CircuitPython_DS2413 pull request #24
Opened 2022-09-22 15:56 UTC by tcfranks

resolves #23 
submitted for review / comment

2022-09-28 01:05 UTC, tekktrik requested changes
Just a few changes!  Thanks for the PR!

2022-09-28 01:05 UTC, tekktrik commented on adafruit_ds2413.py
> +    def value(self, state: Union[bool, Literal[0, 1]]) -> None:
`state` can simply be `bool` here, identical to the getter.

2022-09-28 01:05 UTC, tekktrik commented on adafruit_ds2413.py
> +    def IOA(self) -> Pin:
This should return `DS2413Pin`

2022-09-28 01:05 UTC, tekktrik commented on adafruit_ds2413.py
> +    def IOB(self) -> Pin:
This should also return `DS2413Pin`

2022-09-28 01:55 UTC, tcfranks commented
changes per review comments are ready for review

2022-09-29 03:16 UTC, tekktrik approved these changes
Thanks!

2022-09-29 03:16 UTC, merged